version: "3"
services:
  research:
    build:
      context: research
    ports:
      - 8888:8888
    volumes:
      - ./config.ini.example:/home/jovyan/work/config.ini
      - ./research/deliver:/home/jovyan/work/deliver
      - ./research/data:/home/jovyan/work/data
      - ./research/develop:/home/jovyan/work/develop
      - ./research/src:/home/jovyan/work/src
      - ./research/test:/home/jovyan/work/test
  neo4j:
    image: neo4j:3.1.1
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./research/data/neo4j/data:/data
    environment:
      - NEO4J_AUTH=none
